trigger:
- master

pool:
  vmImage: "ubuntu-16.04"

variables:
  hugo.version: '0.65.3'
  blog.path: './blog'

steps:
# - script: |
#    wget -c https://github.com/gohugoio/hugo/releases/download/v$(hugo.version)/hugo_$(hugo.version)_Linux-64bit.deb   
#   displayName: "Download HUGO"

# - script: 'sudo dpkg -i hugo_$(hugo.version)_Linux-64bit.deb'
#   displayName: "Install HUGO"

# - script: |
#    cd $(blog.path)
#    hugo --log -v
#   displayName: 'Generate Blog'

- task: HugoTask@1
  inputs:
    source: '$(blog.path)'
    destination: '$(blog.path)/public'
    extendedVersion: true
    baseURL: 'owensymesstorageaccount.z26.web.core.windows.net'
    
- task: CopyFiles@2
  displayName: 'Copy Blog'
  inputs:
    SourceFolder: '$(blog.path)/public'
    Contents: "**"
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Blog
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: Drop
    publishLocation: 'Container'
