baseURL = "/"
languageCode = "en-us"
title = "Owen Symes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30
canonifyURLs = true
enableEmoji = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# [[menu.main]]
#    name = "Projects"
#    url = "/projects/"
#    weight = 2

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3

[params]
  google_analytics_id=""
  # homepage_button_link = '/docs'
  # homepage_button_text = 'Read The Docs'
  # homepage_intro = 'Full-stack .NET developer'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Owen's personal website and blog"
    meta_og_title = "Owen Symes"
    meta_og_type = "website"
    meta_og_url = "https://owensym.es"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Owen's personal website and blog."
    meta_twitter_card = "summary"
    meta_twitter_site = "@owensymes"
    meta_twitter_creator = "@owensymes"

  [params.logo]
      mobile = "logo-mobile.png"
      standard  = "logo-desktop.png"